image: node:10

pages:
  cache:
    paths:
      - node_modules/

  script:
    - pwd
    - ls -lah
    - npm install
    - npm run dist
    - npx cpx 'dist/**/!(*.map)' 'public/' -u -v

  artifacts:
    paths:
      - public

  only:
    - master
